service: yuyat-serverless-go-practice

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  role: ${env:AWS_LAMBDA_IAM_ROLE}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
  world:
    handler: bin/world
    events:
      - http:
          path: world
          method: get

  cron:
    handler: bin/cron
    events:
      - schedule: cron(* * * * ? *)
